# Generated by Django 5.2.6 on 2025-09-30 05:27

from django.db import migrations

def populate_game_types(apps, schema_editor):
    """
    Populate default game type values
    """
    GameType = apps.get_model('game_types', 'GameType')
    ServiceType = apps.get_model('service_types', 'ServiceType')

    # Define default game types with their service types
    default_game_types = [
        {'name': 'PS4', 'description': 'PlayStation 4 console', 'service_type_name': 'Console'},
        {'name': 'PS5', 'description': 'PlayStation 5 console', 'service_type_name': 'Console'},
        {'name': 'Quest', 'description': 'Meta Quest VR headset', 'service_type_name': 'Virtual Reality'},
        {'name': 'Wheel', 'description': 'Racing wheel setup', 'service_type_name': 'Driving'},
        {'name': '8 Ball', 'description': '8 Ball pool table', 'service_type_name': 'Table Games'},
    ]

    # Create game type entries
    for game_type_data in default_game_types:
        # Get the service type
        service_type = ServiceType.objects.get(name=game_type_data['service_type_name'])

        GameType.objects.get_or_create(
            name=game_type_data['name'],
            service_type=service_type,
            defaults={
                'description': game_type_data['description'],
                'archive': False,
                'created_by': None,
                'updated_by': None,
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('game_types', '0001_initial'),
        ('service_types', '0002_populate_default_service_types'),
    ]

    operations = [
        migrations.RunPython(populate_game_types),
    ]
