# Generated by Django 5.2.6 on 2025-09-30 04:57

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('durations', '0001_initial'),
        ('game_types', '0001_initial'),
        ('service_types', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalServicePrice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('player_count', models.PositiveIntegerField(blank=True, default=1, help_text='Minimum player count for this pricing', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_player_count', models.PositiveIntegerField(default=1, help_text='Maximum player count for this pricing', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.FloatField(help_text='Price for this service configuration', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('archive', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('duration', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='durations.duration')),
                ('game_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='game_types.gametype')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='service_types.servicetype')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical service price',
                'verbose_name_plural': 'historical service prices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_count', models.PositiveIntegerField(blank=True, default=1, help_text='Minimum player count for this pricing', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_player_count', models.PositiveIntegerField(default=1, help_text='Maximum player count for this pricing', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.FloatField(help_text='Price for this service configuration', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_prices_created', to=settings.AUTH_USER_MODEL)),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='durations.duration')),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='game_types.gametype')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='service_types.servicetype')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_prices_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('service_type', 'game_type', 'duration', 'player_count', 'max_player_count')},
            },
        ),
    ]
