# Generated by Django 5.2.6 on 2025-09-30 06:01

from django.db import migrations


def populate_service_prices(apps, schema_editor):
    """
    Populate default service price values
    """
    ServicePrice = apps.get_model('service_prices', 'ServicePrice')
    ServiceType = apps.get_model('service_types', 'ServiceType')
    GameType = apps.get_model('game_types', 'GameType')
    Duration = apps.get_model('durations', 'Duration')

    # Define default service prices
    default_service_prices = [
        {
            'service_type_name': 'Console',
            'game_type_name': 'PS4',
            'duration_type': 'MINUTE',
            'duration_value': 30.0,
            'player_count': 1,
            'max_player_count': 1,
            'price': 50.0
        },
        {
            'service_type_name': 'Console',
            'game_type_name': 'PS4',
            'duration_type': 'MINUTE',
            'duration_value': 30.0,
            'player_count': 2,
            'max_player_count': 2,
            'price': 50.0
        },
        {
            'service_type_name': 'Console',
            'game_type_name': 'PS4',
            'duration_type': 'MINUTE',
            'duration_value': 30.0,
            'player_count': 3,
            'max_player_count': 3,
            'price': 50.0
        },
        {
            'service_type_name': 'Console',
            'game_type_name': 'PS4',
            'duration_type': 'MINUTE',
            'duration_value': 30.0,
            'player_count': 4,
            'max_player_count': 4,
            'price': 50.0
        },
        {
            'service_type_name': 'Console',
            'game_type_name': 'PS4',
            'duration_type': 'HOUR',
            'duration_value': 1.0,
            'player_count': 1,
            'max_player_count': 1,
            'price': 80.0
        },
        {
            'service_type_name': 'Console',
            'game_type_name': 'PS4',
            'duration_type': 'HOUR',
            'duration_value': 1.0,
            'player_count': 2,
            'max_player_count': 2,
            'price': 100.0
        },
        {
            'service_type_name': 'Console',
            'game_type_name': 'PS4',
            'duration_type': 'HOUR',
            'duration_value': 1.0,
            'player_count': 3,
            'max_player_count': 3,
            'price': 120.0
        },
        {
            'service_type_name': 'Console',
            'game_type_name': 'PS4',
            'duration_type': 'HOUR',
            'duration_value': 1.0,
            'player_count': 4,
            'max_player_count': 4,
            'price': 140.0
        },
        {
            'service_type_name': 'Console',
            'game_type_name': 'PS5',
            'duration_type': 'HOUR',
            'duration_value': 1.0,
            'player_count': 1,
            'max_player_count': 1,
            'price': 120.0
        },
        {
            'service_type_name': 'Console',
            'game_type_name': 'PS5',
            'duration_type': 'HOUR',
            'duration_value': 1.0,
            'player_count': 2,
            'max_player_count': 2,
            'price': 150.0
        },
        {
            'service_type_name': 'Console',
            'game_type_name': 'PS5',
            'duration_type': 'HOUR',
            'duration_value': 1.0,
            'player_count': 3,
            'max_player_count': 3,
            'price': 180.0
        },
        {
            'service_type_name': 'Console',
            'game_type_name': 'PS5',
            'duration_type': 'HOUR',
            'duration_value': 1.0,
            'player_count': 4,
            'max_player_count': 4,
            'price': 200.0
        },
        {
            'service_type_name': 'Console',
            'game_type_name': 'PS5',
            'duration_type': 'MINUTE',
            'duration_value': 30.0,
            'player_count': 1,
            'max_player_count': 1,
            'price': 70.0
        },
        {
            'service_type_name': 'Console',
            'game_type_name': 'PS5',
            'duration_type': 'MINUTE',
            'duration_value': 30.0,
            'player_count': 2,
            'max_player_count': 2,
            'price': 90.0
        },
        {
            'service_type_name': 'Console',
            'game_type_name': 'PS5',
            'duration_type': 'MINUTE',
            'duration_value': 30.0,
            'player_count': 3,
            'max_player_count': 3,
            'price': 100.0
        },
        {
            'service_type_name': 'Console',
            'game_type_name': 'PS5',
            'duration_type': 'MINUTE',
            'duration_value': 30.0,
            'player_count': 4,
            'max_player_count': 4,
            'price': 120.0
        },
        {
            'service_type_name': 'Virtual Reality',
            'game_type_name': 'Quest',
            'duration_type': 'MINUTE',
            'duration_value': 15.0,
            'player_count': 1,
            'max_player_count': 1,
            'price': 120.0
        },
        {
            'service_type_name': 'Virtual Reality',
            'game_type_name': 'Quest',
            'duration_type': 'MINUTE',
            'duration_value': 30.0,
            'player_count': 1,
            'max_player_count': 1,
            'price': 120.0
        },
        {
            'service_type_name': 'Virtual Reality',
            'game_type_name': 'Quest',
            'duration_type': 'HOUR',
            'duration_value': 1.0,
            'player_count': 1,
            'max_player_count': 1,
            'price': 120.0
        },
        {
            'service_type_name': 'Driving',
            'game_type_name': 'Wheel',
            'duration_type': 'MINUTE',
            'duration_value': 30.0,
            'player_count': 1,
            'max_player_count': 1,
            'price': 50.0
        },
        {
            'service_type_name': 'Driving',
            'game_type_name': 'Wheel',
            'duration_type': 'HOUR',
            'duration_value': 1.0,
            'player_count': 1,
            'max_player_count': 1,
            'price': 100.0
        },
        {
            'service_type_name': 'Table Games',
            'game_type_name': '8 Ball',
            'duration_type': 'HOUR',
            'duration_value': 1.0,
            'player_count': 4,
            'max_player_count': 4,
            'price': 200.0
        },
    ]

    # Create service price entries
    for price_data in default_service_prices:
        # Get related objects
        service_type = ServiceType.objects.get(name=price_data['service_type_name'])
        game_type = GameType.objects.get(
            name=price_data['game_type_name'],
            service_type=service_type
        )
        duration = Duration.objects.get(
            type=price_data['duration_type'],
            duration=price_data['duration_value']
        )

        ServicePrice.objects.get_or_create(
            service_type=service_type,
            game_type=game_type,
            duration=duration,
            player_count=price_data['player_count'],
            max_player_count=price_data['max_player_count'],
            defaults={
                'price': price_data['price'],
                'archive': False,
                'created_by': None,
                'updated_by': None,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('service_prices', '0001_initial'),  # Update this to match your last migration
        ('service_types', '0002_populate_default_service_types'),
        ('game_types', '0002_populate_default_game_types'),
        ('durations', '0002_populate_default_durations'),
    ]

    operations = [
        migrations.RunPython(populate_service_prices),
    ]
