# Generated by Django 5.2.6 on 2025-09-25 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_services', '0002_remove_gamingservice_name_and_more'),
        ('gaming_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamingsession',
            name='service',
        ),
        migrations.RemoveField(
            model_name='historicalgamingsession',
            name='service',
        ),
        migrations.AddField(
            model_name='gamingsession',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gaming_sessions_station', to='gaming_services.station'),
        ),
        migrations.AddField(
            model_name='historicalgamingsession',
            name='station',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gaming_services.station'),
        ),
    ]
