# Generated by Django 5.2.6 on 2025-10-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamingsession',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historicalgamingsession',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
