# Generated by Django 5.2.6 on 2025-09-27 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durations', '0001_initial'),
        ('gaming_sessions', '0002_remove_gamingsession_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamingsession',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gaming_sessions_duration', to='durations.duration'),
        ),
        migrations.AddField(
            model_name='historicalgamingsession',
            name='duration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='durations.duration'),
        ),
    ]
