# Generated by Django 5.2.6 on 2025-10-03 18:57

from django.db import migrations

def populate_roles(apps, schema_editor):
    """Populate Role table with default roles"""
    Role = apps.get_model('roles', 'Role')
    User = apps.get_model('auth', 'User')

    # Get the first superuser or create a system user
    try:
        admin_user = User.objects.filter(is_superuser=True).first()
    except User.DoesNotExist:
        admin_user = None

    # Define default roles
    roles = [
        {
            'role_name': 'Admin',
            'description': 'Administrator with full access to the system',
        },
        {
            'role_name': 'Customer',
            'description': 'Regular customer with limited access',
        },
    ]

    # Create roles if they don't exist
    for role_data in roles:
        Role.objects.get_or_create(
            role_name=role_data['role_name'],
            defaults={
                'description': role_data['description'],
                'created_by': admin_user,
                'updated_by': admin_user,
                'archive': False,
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_roles),
    ]
