# Generated by Django 5.2.6 on 2025-09-30 05:08

from django.db import migrations

def populate_default_durations(apps, schema_editor):
    Duration = apps.get_model('durations', 'Duration')

    default_durations = [
        {'type': 'MINUTE', 'duration': 15.0},
        {'type': 'MINUTE', 'duration': 30.0},
        {'type': 'HOUR', 'duration': 1.0},
        {'type': 'HOUR', 'duration': 2.0},
    ]

    # Create the durations
    for duration_data in default_durations:
        Duration.objects.get_or_create(
            type=duration_data['type'],
            duration=duration_data['duration'],
            defaults={
                'archive': False,
                'created_by': None,
                'updated_by': None
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('durations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_default_durations),
    ]
