# Generated by Django 5.2.6 on 2025-09-30 05:19

from django.db import migrations

def populate_default_service_types(apps, schema_editor):
    ServiceType = apps.get_model('service_types', 'ServiceType')

    # Define default service types
    default_service_types = [
        {'name': 'Console', 'description': 'Gaming console services'},
        {'name': 'Virtual Reality', 'description': 'VR gaming experiences'},
        {'name': 'Driving', 'description': 'Driving simulation services'},
        {'name': 'Table Games', 'description': 'Table-based gaming services'},
    ]

    # Create service type entries
    for service_type_data in default_service_types:
        ServiceType.objects.get_or_create(
            name=service_type_data['name'],
            defaults={
                'description': service_type_data['description'],
                'archive': False,
                'created_by': None,
                'updated_by': None,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('service_types', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_default_service_types),
    ]
