# Generated by Django 5.2.6 on 2025-09-30 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstation',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='station',
            name='service_type',
        ),
    ]
