# Generated by Django 5.2.6 on 2025-09-30 05:36

from django.db import migrations

def populate_stations(apps, schema_editor):
    """
    Populate default station values
    """
    Station = apps.get_model('stations', 'Station')
    GameType = apps.get_model('game_types', 'GameType')

    # Define default stations with their game types
    default_stations = [
        {'name': 'Station 1', 'game_type_name': 'PS4', 'description': 'PS4 gaming station'},
        {'name': 'Station 2', 'game_type_name': 'PS4', 'description': 'PS4 gaming station'},
        {'name': 'Station 3', 'game_type_name': 'PS5', 'description': 'PS5 gaming station'},
        {'name': 'Station 4', 'game_type_name': 'Quest', 'description': 'VR gaming station'},
        {'name': 'Station 5', 'game_type_name': 'Wheel', 'description': 'Driving simulation station'},
        {'name': 'Station 6', 'game_type_name': '8 Ball', 'description': 'Pool table station'},
    ]

    # Create station entries
    for station_data in default_stations:
        # Get the game type
        game_type = GameType.objects.get(name=station_data['game_type_name'])

        Station.objects.get_or_create(
            name=station_data['name'],
            defaults={
                'description': station_data['description'],
                'game_type': game_type,
                'is_active': True,
                'archive': False,
                'created_by': None,
                'updated_by': None,
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_remove_historicalstation_service_type_and_more'),
        ('game_types', '0002_populate_default_game_types'),
    ]

    operations = [
        migrations.RunPython(populate_stations),
    ]
