# Generated by Django 5.2.6 on 2025-09-25 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamingservice',
            name='name',
        ),
        migrations.AlterField(
            model_name='gamingservice',
            name='service_type',
            field=models.CharField(choices=[('PS4', 'PlayStation 4'), ('PS5', 'PlayStation 5'), ('PC', 'PC'), ('VR', 'VR'), ('DRIVING', 'Driving Simulator')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations_created', to=settings.AUTH_USER_MODEL)),
                ('gaming_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='gaming_services.gamingservice')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
