# Generated by Django 5.2.6 on 2025-09-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming_services', '0002_remove_gamingservice_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
